PREFIX ex: <http://www.hobbiton.com/schema>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <https://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  # Specify product_iri as a Class and specify subject-object relationships
  ?product_iri rdf:type rdfs:Class ;
    ex:isProduct ?Product ;
    ex:producedBy ?farmer_iri ;
    ex:producedOn ?date ;
    ex:hasCount ?count .
}

FROM <file:farming.csv>

WHERE {
  BIND(REPLACE(STR(?Product),"[ ]","_") AS ?product)
  BIND(IRI(CONCAT('http://www.hobbiton.com/schema/product#', ?product)) AS ?product_iri)
  BIND(xsd:integer(?Count) AS ?count)
  BIND(xsd:date(?Date) AS ?date)
}